# Site settings
title: whinaal.github.io
email: whinaayulestari18@gmail.com
author: Whina Ayu Lestari 
description: "Speech of Machine and Human Contemplations"
baseurl: ""
url: "http://whinaal.github.io"
twitter_username: whinaal
github_username:  whinaal
linkedin_username: whina ayu lestari

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap
